name: Deploy to GitHub Pages with Bun

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 簽出代碼
      - name: Checkout
        uses: actions/checkout@v3

      # 2. 安裝 Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1.2.5
        with:
          bun-version: 1.2.5 # 或指定版本，例如 "1.0.0"

      # 3. 安裝依賴
      - name: Install Dependencies
        run: bun install

      # 4. 構建專案
      - name: Build
        run: bun run build

      - name: List dist contents
        run: ls -la dist/ || dir dist  # 檢查 dist 內容，根據系統選擇 ls 或 dir

      # 5. 部署到 GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true  # 強制創建新的 gh-pages 分支